apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: DB-Search-Stack
spec:
  description: MariaDB 11.4 LTS 與 Elasticsearch 的優化環境
  icon: https://cdn.zeabur.com/mariadb.svg
  coverImage: https://zeabur.com/docs/_next/image?url=%2Fdocs%2F_next%2Fstatic%2Fmedia%2Fintro.5b73c4f8.png&w=3840&q=75

  variables:
    - key: MARIADB_PASSWORD
      type: PASSWORD
      name: MariaDB Root Password
      description: 請設定 MariaDB 的管理員密碼

  tags:
    - Database
    - Search Engine
    - Migration

  resourceUsage:
    cpu: 2
    memory: 4096

  services:
    # --- 1. MariaDB ---
    - name: mariadb
      icon: https://cdn.zeabur.com/mariadb.svg
      template: PREBUILT
      spec:
        source:
          image: mariadb:11.4 # <--- 依照您的要求直接指定 image
        ports:
          - id: mysql-port
            port: 3306
            type: TCP
        volumes:
          - id: db-data
            dir: /var/lib/mysql
        resources:
          cpu: 500
          memory: 1024
      env:
        MARIADB_ROOT_PASSWORD:
          default: ${MARIADB_PASSWORD}

    # --- 2. Elasticsearch ---
    - name: elasticsearch
      icon: https://cdn.worldvectorlogo.com/logos/elasticsearch.svg
      template: PREBUILT
      spec:
        source:
          image: ghcr.io/taiwannews/es-with-ik:latest
        ports:
          - id: es-http
            port: 9200
            type: HTTP
        volumes:
          - id: es-data
            dir: /usr/share/elasticsearch/data
        resources:
          cpu: 1000
          memory: 2048
      env:
        discovery.type:
          default: 'single-node'
        xpack.security.enabled:
          default: 'false'
        ES_JAVA_OPTS:
          default: '-Xms1g -Xmx1g'

    # --- 3. Redis ---
    - name: redis
      icon: https://service-icons.zeabur.com/marketplace/redis.svg
      template: PREBUILT
      spec:
        source:
          image: redis:7-alpine # <--- 依照您的要求直接指定 image
        ports:
          - id: redis-port
            port: 6379
            type: TCP
        volumes:
          - id: redis-data
            dir: /data
        resources:
          cpu: 200
          memory: 256

localization:
  zh-TW:
    description: 針對 MySQL 8.0 搬遷至 MariaDB 11 LTS 與 ES (IK) 的高效能堆疊。
